name: Share data between jobs

on: [push]

jobs:
  job_1:
    name: Add 13 and 17
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 13 + 17 > math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: homework
          path: math-homework.txt
